### ISSUE TITLE
Peak Filter "Peak classifier" - feature request

### ISSUE THREAD

**Issue by danield5732** [OpenChrom/openchrom#46] opened 2020-04-20 07:41 UTC
Feature request for options to
- classify peaks only if they donot have a classifier yet
- override existing classifiers
- classify peaks only if they have a name

Since in the current version .* leads to the behaviour of the latter request, these are all minor issues.

**Comment by Mailaender** [comment] 2022-08-23 13:14
Reverse duplicate of https://github.com/eclipse/chemclipse/issues/324.

**Closed as completed by Mailaender** 2022-08-23 13:14 UTC
Labels: enhancement
